name: flexdash_map

on:
  push:
    branches:
     - main

jobs:
  build:
    name: flexdashboard map
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
    
      - name: Render Rmarkdown
        run: |
          Rscript -e "rmarkdown::render('index.Rmd')"
      - name: commit
        env:
         GITHUB_TOKEN: ${{secrets.GH_TOKEN}} 
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "{{ github.actor }}"
          git commit -am 'Re-run scrape_nepse_data.R' || echo "No changes to commit"
          git push -u origin HEAD:${{ github.ref }} || echo "Error in Push"
